GET http://localhost:3000/api/v1/products

###

POST http://localhost:3000/api/v1/products
content-type: application/json

{
  "sku": "String",
  "title": "String",
  "description": "String",
  "manufactureDetails": {
    "modelNumber":1221
  },
  "quantity":111,
  "pricing":{
    "price":0
  }
}
